import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const outfit = Outfit({
  subsets: ['latin']
}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", outfit.className)}
    >
      <body className="min-h-full flex flex-col">
        {children}
      <Toaster richColors position="top-right"/>
      </body>
    </html>
  );
}
